package com.example.funpet;

public class ImageDatabase {

    Integer[] dogs ={

            R.drawable.beagle_1,
            R.drawable.chihua_2,
            R.drawable.doberman_3,
            R.drawable.golden_4,
            R.drawable.husky_5,
            R.drawable.pug_6,
            R.drawable.rottweiler_7,
            R.drawable.shepherd_8,
            R.drawable.spaniel_9,
            R.drawable.entlebucher_1,
            R.drawable.basset_1,
            R.drawable.blenheim_1,
            R.drawable.bloodhound_1,
            R.drawable.bluetick_1,
            R.drawable.borzoi_1,
            R.drawable.bullterrier_1,
            R.drawable.deerhound_1,
            R.drawable.foxhound_1,
            R.drawable.hound_1,
            R.drawable.maltese_1,
            R.drawable.papillon_1,
            R.drawable.pekinese_1,
            R.drawable.redbone_1,
            R.drawable.ridgeback_1,
            R.drawable.saluki_1,
            R.drawable.shihtzu_1,
            R.drawable.terrior_1,
            R.drawable.walkerhound_1,
            R.drawable.weimarana_1,
            R.drawable.whippet_1,
            R.drawable.wolfhound_1,
            R.drawable.affenpinsher_1,
            R.drawable.basenji_1,
            R.drawable.cardigan_1,
            R.drawable.chow_1,
            R.drawable.dhole_1,
            R.drawable.dingo_1,
            R.drawable.eskimodog_1,
            R.drawable.griffon_1,
            R.drawable.hairless_1,
            R.drawable.hauntingdog_1,
            R.drawable.keeshond_1,
            R.drawable.leonberg_1,
            R.drawable.malamute_1,
            R.drawable.newfoundland_1,
            R.drawable.pembroke_1,
            R.drawable.pomeranion_1,
            R.drawable.poodle_1,
            R.drawable.pyrenees_1,
            R.drawable.samoyed_1,
            R.drawable.toypoodle_1,



    };

    String[] dogNames= {
            "Beagle",
            "Chihuahua",
            "Doberman",
            "Golden Retriever",
            "Siberian husky",
            "Pug",
            "Rottweiler",
            "German Shepherd",
            "Japanese spaniel",
            "EntleBucher",
            "Basset",
            "Blenheim spaniel",
            "Bloodhound",
            "Bluetick",
            "Borzoi",
            "Staffordshire bullterrier",
            "Scottish deerhound",
            "English foxhound",
            "Afghan hound",
            "Maltese dog",
            "Papillon",
            "Pekinese",
            "Redbone",
            "Rhodesian ridgeback",
            "Saluki",
            "Shih-Tzu",
            "Toy terrier",
            "Walker hound",
            "Weimaraner",
            "Whippet",
            "Irish wolfhound",
            "Affenpinscher",
            "Basenji",
            "Cardigan",
            "Chow",
            "Dhole",
            "Dingo",
            "Eskimo dog",
            "Brabancon griffon",
            "Mexican hairless",
            "African hunting dog",
            "Keeshond",
            "Leonberg",
            "Malamute",
            "Newfoundland",
            "Pembroke",
            "Pomeranian",
            "Standard_poodle",
            "Great Pyrenees",
            "Samoyed",
            "Toy poodle",
    };
}
